image: python:latest

test:
  stage: test
  script:
    - pip install pip
    - python -V
    - pip install tox
    - tox


pages:
  stage: deploy
  image: ruby

  script:
    - gem install compass zurb-foundation # CSS stylesheets generation
    - gem install prawn -v 2.1.0
    - gem install asciidoctor # HTML generationr
    - gem install asciidoctor-pdf --pre
    - gem install wkhtmltox
    - chmod +x scripts/run-tests.sh
    - ./scripts/run-tests.sh

  artifacts:
    paths:
    - public

  only:
  - master