image: python:3.8

test:
  stage: test
  script:
    - gem install compass zurb-foundation # CSS stylesheets generation
    - gem install prawn -v 2.1.0
    - gem install asciidoctor # HTML generationr
    - gem install asciidoctor-pdf --pre
    - gem install wkhtmltox
    - pip install pip
    - python -V
    - python -m pip install --user tox
    - chmod +x scripts/run-tests.sh
    - ./scripts/run-tests.sh


pages:
  stage: deploy
  image: ruby

  script: skip
  artifacts:
    paths:
    - public

  only:
  - master