image: python:3.8

test:
  stage: test
  script:
    - pip install pip
    - python -V
    - pip install tox
    - tox

pages:
  stage: deploy
  image: ruby

  script:
    - gem install compass zurb-foundation # CSS stylesheets generation
    - gem install prawn -v 2.1.0
    - gem install asciidoctor # HTML generationr
    - gem install asciidoctor-pdf --pre
    - gem install wkhtmltox
    - mkdir public
    - cd public
    - echo "hello tout le monde" > text1.adoc
    - asciidoctor-pdf text1.adoc -o documentation.pdf
    - asciidoctor text1.adoc -o index.html
    - cd ..

  artifacts:
    paths:
    - public

  only:
  - master